### ISSUE TITLE
Evaluation of Taiwan LLaMa v1.0 and ChatGPT (gpt3.5-turbo-0613) on TTQA Dataset

### ISSUE THREAD

**Issue by adamlin120** [mtkresearch/MR-Models#1]
Hi MediaTek Research,

I am writing to share the results of a quick evaluation conducted on the TTQA (Taiwan Trivia Question Answering) dataset with two models: Taiwan LLaMa v1.0 and ChatGPT (gpt3.5-turbo-0613). The 0-shot performance was examined for both models.

### Results:
- **Taiwan LLaMa v1.0**: 48 / 64
- **ChatGPT (gpt3.5-turbo-0613)**: 48 / 64

The full prediction and  evaluation can be found in this JSON file: [TTQA_1.0.0_tw_llama_v1.0.json](https://github.com/MiuLab/Taiwan-LLaMa/blob/main/evaluation/TTQA_1.0.0_tw_llama_v1.0.json).

I have manually compared the model's predictions with the reference answers. If there are any disagreements or concerns regarding the evaluation, I would be happy to discuss them with the original authors.

Thank you for making the TTQA dataset available!

Yen-Ting

**Comment by GitYCC** [comment]
Thank you for your using and sharing. Taiwan LLaMA is quite impressive.
