### ISSUE TITLE
IMDB-TC license

### ISSUE THREAD

**Issue by TobyOoO** [mtkresearch/MR-Models#13]
Hello authors.

I'd like to check that this is a subset of IMDB Review dataset hosted on kaggle here:
https://www.kaggle.com/datasets/pawankumargunjan/imdb-review

The page claimed that it's licensed under GNU LGPL v3, however in the repo you said it's under Apache 2.0
As machine translation is not covered by copyright, I'd like to confirm which license is correct.

**Comment by cll-mtk** [comment]
We have updated the license information of each benchmark.
